# Generated by Django 4.2.6 on 2023-10-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tip_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='attachments',
        ),
        migrations.AddField(
            model_name='tip',
            name='file_attachment',
            field=models.FileField(default=1, upload_to='attachments/'),
            preserve_default=False,
        ),
    ]
