# Generated by Django 4.2.5 on 2023-11-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_tip_attachments_tip_file_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='file_attachment',
            field=models.FileField(upload_to='main/attachments/'),
        ),
    ]
